version: '3.9'

services:
  web:
    build: .
    container_name: "django_server"
    command: [ "sh", "-c", "poetry run python manage.py migrate &&
      poetry run python manage.py crontab add && cron &&
      poetry run python manage.py runserver 0.0.0.0:8000" ]

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "docker-compose logs -t django_server | grep -q 'Starting development server at'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s  # Delay before starting health checks after container is started

volumes:
  postgres_data:
