[tool.poetry]
name = "dev-skill-compass-server"
version = "0.1.0"
description = ""
authors = ["Koren <korenkpalan96@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.6"
djangorestframework = "^3.15.1"
psycopg2-binary = "^2.9.9"
python-dotenv = "^1.0.1"
selenium = "^4.21.0"
beautifulsoup4 = "^4.12.3"
requests = "^2.32.0"
spacy = "^3.7.4"
nltk = "^3.8.1"
pytest-django = "^4.8.0"
django-crontab = "^0.7.1"



[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
