# Generated by Django 5.0.6 on 2024-05-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table=None,
        ),
        migrations.AlterModelTable(
            name='roles',
            table=None,
        ),
        migrations.AlterModelTable(
            name='technologies',
            table=None,
        ),
    ]
