# Generated by Django 5.0.6 on 2024-06-17 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rolelistingscount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolelistingscount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="rolelistingscount",
            index=models.Index(
                fields=["role_id", "created_at"], name="core_roleli_role_id_23e7d5_idx"
            ),
        ),
    ]
