# Generated by Django 5.0.6 on 2024-05-24 11:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTopTechnologies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counter', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.roles')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.technologies')),
            ],
            options={
                'db_table': 'historicalTopTechnologies',
            },
        ),
        migrations.CreateModel(
            name='TechnologiesCounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counter', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.roles')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.technologies')),
            ],
            options={
                'db_table': 'TechnologiesCounts',
            },
        ),
    ]
