# Generated by Django 5.0.6 on 2024-05-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltoptechnologies',
            old_name='role',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='historicaltoptechnologies',
            old_name='technology',
            new_name='technology_id',
        ),
        migrations.RenameField(
            model_name='technologiescounts',
            old_name='role',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='technologiescounts',
            old_name='technology',
            new_name='technology_id',
        ),
        migrations.AlterField(
            model_name='historicaltoptechnologies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='technologiescounts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='historicaltoptechnologies',
            table=None,
        ),
        migrations.AlterModelTable(
            name='technologiescounts',
            table=None,
        ),
    ]
