# Generated by Django 5.0.6 on 2024-06-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rolelistingscount_and_more"),
        ("usage_stats", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aggregatedtechcounts",
            index=models.Index(
                fields=["role_id", "technology_id"],
                name="usage_stats_role_id_c149ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historicaltechcounts",
            index=models.Index(
                fields=["role_id", "technology_id"],
                name="usage_stats_role_id_e92c78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historicaltechcounts",
            index=models.Index(
                fields=["created_at"], name="usage_stats_created_ca6e83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlytechnologiescounts",
            index=models.Index(
                fields=["role_id", "technology_id"],
                name="usage_stats_role_id_77df85_idx",
            ),
        ),
    ]
