# Generated by Django 5.0.6 on 2024-05-27 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologiescounts',
            name='counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
