---
name: CI-CD

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Lint
        run: docker-compose run --rm web sh -c "flake8"
      - name: Test
        run: pytest